services:
  paddle-v5-test:
    container_name: paddle-v5-test
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "1008:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000