services:
  paddleocr-api:
    container_name: paddleocr-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1006:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    command: /app/.venv/bin/fastapi run app/main.py --host 0.0.0.0 --port 8000